### ISSUE TITLE
Keep alive time

### ISSUE THREAD

**Issue by NazaretRJ** [labplus-cn/mpython-docs#4]
¡Hi!

In the documentation is not clear to know which is the units of the keep alive time (For example, if it is miliseconds or secons).
Also If you use the last will topic you should specify the keepalive time.

Best Regards.

**Comment by lgnativs** [comment]
> ¡Hi!
> 
> In the documentation is not clear to know which is the units of the keep alive time (For example, if it is miliseconds or secons). Also If you use the last will topic you should specify the keepalive time.
> 
> Best Regards.

Thank you for your report, a comment about MQTT Keep Alive has been added
